#!/usr/bin/env python3
"""Truth tests for data/encounters.v2.json (generated by tools/build_encounters.py). No engine needed."""
import json, sys
from pathlib import Path
try:
    import chess
except ImportError:
    print("python-chess required"); sys.exit(1)
DATA = Path(__file__).resolve().parents[1] / "data" / "encounters.v2.json"
MATE, MARGIN = 10000, 150
def test():
    data = json.loads(DATA.read_text())
    packs = {}
    for e in data: packs.setdefault(e.get("pack", "tactics"), []).append(e)
    assert len(packs["tactics"]) == 12, "tactics pack holds 12 fights"
    assert len(packs.get("openings", [])) >= 5, "openings pack needs at least 5 fights"
    ids = [e["id"] for e in data]; assert len(ids) == len(set(ids)), "ids unique across packs"
    for e in data:
        board = chess.Board(e["fen"]); assert board.is_valid(), e["id"]
        best, bait = chess.Move.from_uci(e["best"]), chess.Move.from_uci(e["bait"])
        assert best in board.legal_moves and bait in board.legal_moves, e["id"]
        assert board.san(best) == e["bestSan"] and board.san(bait) == e["temptingSan"], e["id"]
        legal = {m.uci() for m in board.legal_moves}
        assert set(e["moves"]) == legal, e["id"] + " every legal move scored, nothing else"
        sb, sbait = e["moves"][e["best"]]["cp"], e["moves"][e["bait"]]["cp"]
        assert (sb >= MATE - 100 and sbait < MATE - 100) or sb - sbait >= MARGIN, e["id"] + " margin"
        assert e["moves"][e["best"]]["tier"] == "best" and e["moves"][e["bait"]]["tier"] == "bait", e["id"]
        top = max(m["cp"] for m in e["moves"].values()); assert top - sb <= max(10, abs(top) * 0.04), e["id"] + " best is top"
        for key in ("bestLineUci", "temptingLineUci"):
            b = board.copy(); line = e[key]; assert 1 <= len(line) <= 5, e["id"]
            for u in line: mv = chess.Move.from_uci(u); assert mv in b.legal_moves, f"{e['id']} {key} illegal {u}"; b.push(mv)
        assert e["bestLineUci"][0] == e["best"] and e["temptingLineUci"][0] == e["bait"], e["id"]
        at = e["whyTargets"].get("at"); assert at in ("before", "after"), e["id"] + " whyTargets.at"
        gate = board.copy()
        if at == "after": gate.push(best)
        for sq in e["whyTargets"]["squares"]:
            s = chess.parse_square(sq)
            assert board.piece_at(s) is not None, f"{e['id']} whyTarget {sq} empty at start"
            assert gate.piece_at(s) is not None, f"{e['id']} whyTarget {sq} empty in the {at} gate position"
            if at == "after":
                p0, p1 = board.piece_at(s), gate.piece_at(s)
                assert p0.piece_type == p1.piece_type and p0.color == p1.color, f"{e['id']} whyTarget {sq} changed after the move; gate should be 'before'"
        assert len(e["whyTargets"]["prompt"].split()) <= 12, e["id"] + " prompt too long"
        for k in ("taunt", "gloat", "rage"): assert 3 <= len(e["glitch"][k].split()) <= 14, f"{e['id']} glitch {k}"
        assert e["best"][:2] in e["candidates"], e["id"] + " candidates"
    assert sum(1 for e in packs["tactics"] if e["boss"]) == 3, "three bosses in the tactics pack"
    for e in data:
        assert chess.Board(e["fen"]).turn == chess.WHITE, e["id"] + " arena positions are always white to move"
    print("OK encounters v2: %d fights in %d packs — legality, margins, tiers, lines, gate positions, bosses" % (len(data), len(packs)) + "")
if __name__ == "__main__":
    test()
