#!/usr/bin/env python3
"""Truth tests for data/encounters.v2.json (generated by tools/build_encounters.py). No engine needed."""
import json, sys
from pathlib import Path
try:
    import chess
except ImportError:
    print("python-chess required"); sys.exit(1)
DATA = Path(__file__).resolve().parents[1] / "data" / "encounters.v2.json"
MATE, MARGIN = 10000, 150
def test():
    data = json.loads(DATA.read_text()); assert len(data) == 12
    for e in data:
        board = chess.Board(e["fen"]); assert board.is_valid(), e["id"]
        best, bait = chess.Move.from_uci(e["best"]), chess.Move.from_uci(e["bait"])
        assert best in board.legal_moves and bait in board.legal_moves, e["id"]
        assert board.san(best) == e["bestSan"] and board.san(bait) == e["temptingSan"], e["id"]
        legal = {m.uci() for m in board.legal_moves}
        assert set(e["moves"]) == legal, e["id"] + " every legal move scored, nothing else"
        sb, sbait = e["moves"][e["best"]]["cp"], e["moves"][e["bait"]]["cp"]
        assert (sb >= MATE - 100 and sbait < MATE - 100) or sb - sbait >= MARGIN, e["id"] + " margin"
        assert e["moves"][e["best"]]["tier"] == "best" and e["moves"][e["bait"]]["tier"] == "bait", e["id"]
        top = max(m["cp"] for m in e["moves"].values()); assert top - sb <= max(10, abs(top) * 0.04), e["id"] + " best is top"
        for key in ("bestLineUci", "temptingLineUci"):
            b = board.copy(); line = e[key]; assert 1 <= len(line) <= 5, e["id"]
            for u in line: mv = chess.Move.from_uci(u); assert mv in b.legal_moves, f"{e['id']} {key} illegal {u}"; b.push(mv)
        assert e["bestLineUci"][0] == e["best"] and e["temptingLineUci"][0] == e["bait"], e["id"]
        for sq in e["whyTargets"]["squares"]: assert board.piece_at(chess.parse_square(sq)) is not None, f"{e['id']} whyTarget {sq}"
        assert len(e["whyTargets"]["prompt"].split()) <= 12, e["id"] + " prompt too long"
        for k in ("taunt", "gloat", "rage"): assert 3 <= len(e["glitch"][k].split()) <= 14, f"{e['id']} glitch {k}"
        assert e["best"][:2] in e["candidates"], e["id"] + " candidates"
    assert sum(1 for e in data if e["boss"]) == 3, "three bosses"
    print("OK encounters v2: legality, margins, tiers, lines, why targets, glitch lines, bosses")
if __name__ == "__main__":
    test()
