#!/usr/bin/env python3
"""Build data/encounters.v2.json and web/encounters.js from data/encounters.src.json.
Scores every legal move with Stockfish, assigns fairness tiers, derives futures lines from engine PVs,
and asserts the authoring rule (best beats bait by >=150 cp or mate vs no mate). Run: python3 tools/build_encounters.py [--sf PATH]"""
import json, sys, shutil, chess, chess.engine
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SRC, OUT_JSON, OUT_JS = ROOT/"data/encounters.src.json", ROOT/"data/encounters.v2.json", ROOT/"web/encounters.js"
MATE, GOOD_GAP, BEST_GAP, MARGIN, DEPTH, PV_DEPTH, BOSS = 10000, 60, 10, 150, 14, 16, {"04", "08", "12"}

def sf_path():
    if "--sf" in sys.argv: return sys.argv[sys.argv.index("--sf") + 1]
    return shutil.which("stockfish") or "/tmp/sf/stockfish/stockfish-ubuntu-x86-64-avx2"

def cp_of(score):
    s = score.pov(chess.WHITE)
    if s.is_mate():
        m = s.mate(); return (MATE - m) if m > 0 else -(MATE + m)
    return s.score()

def truncate_line(board, pv):
    """Ply 1 always. Then add plies until (inclusive) the first capture or mate, max 5."""
    line, b = [], board.copy()
    for i, mv in enumerate(pv[:5]):
        cap, b2 = b.is_capture(mv), b.copy(); b2.push(mv)
        line.append(mv.uci()); b = b2
        if b.is_checkmate() or (i > 0 and cap): break
    # keep only ply 1 if no capture/mate was ever reached
    b = board.copy(); reached = False
    for i, u in enumerate(line):
        mv = chess.Move.from_uci(u); cap = b.is_capture(mv); b.push(mv)
        if b.is_checkmate() or (i > 0 and cap): reached = True
    return line if reached else line[:1]

def pack(board):
    s = ""
    for sq, pc in sorted(board.piece_map().items(), key=lambda kv: chess.square_name(kv[0])):
        s += ("w" if pc.color else "b") + pc.symbol().lower() + chess.square_name(sq)
    return s

def legal_pack(board):
    out = {}
    for mv in board.legal_moves:
        fr = chess.square_name(mv.from_square); san = board.san(mv)
        out.setdefault(fr, []).append(mv.uci() + ("x" if board.is_capture(mv) else "") + ":" + san)
    return {k: ",".join(v) for k, v in out.items()}

def build(engine, e):
    board = chess.Board(e["fen"]); assert board.is_valid(), e["id"]
    best, bait = chess.Move.from_uci(e["best"]), chess.Move.from_uci(e["bait"])
    assert best in board.legal_moves and bait in board.legal_moves, e["id"] + " best/bait illegal"
    scores = {}
    for mv in board.legal_moves:
        board.push(mv)
        if board.is_checkmate(): scores[mv.uci()] = MATE
        elif board.is_stalemate() or board.is_insufficient_material(): scores[mv.uci()] = 0
        else: scores[mv.uci()] = cp_of(engine.analyse(board, chess.engine.Limit(depth=DEPTH, time=0.8))["score"])
        board.pop()
    top = max(scores.values())
    best_gap, good_gap = max(BEST_GAP, abs(top) * 0.04), max(GOOD_GAP, abs(top) * 0.12)
    sb, sbait = scores[e["best"]], scores[e["bait"]]
    assert top - sb <= best_gap, f"{e['id']}: engine prefers another move over best {e['best']} ({top} vs {sb})"
    assert (sb >= MATE - 100 and sbait < MATE - 100) or sb - sbait >= MARGIN, f"{e['id']}: margin too small best={sb} bait={sbait}"
    moves = {}
    for mv in board.legal_moves:
        u = mv.uci(); gap = top - scores[u]
        tier = "bait" if u == e["bait"] else "best" if gap <= best_gap else "good" if gap < good_gap else "blunder"
        moves[u] = {"san": board.san(mv), "cp": scores[u], "tier": tier}
    pv_best = engine.analyse(board, chess.engine.Limit(depth=PV_DEPTH, time=1.5), root_moves=[best])["pv"]
    pv_bait = engine.analyse(board, chess.engine.Limit(depth=PV_DEPTH, time=1.5), root_moves=[bait])["pv"]
    best_line, bait_line = truncate_line(board, pv_best), truncate_line(board, pv_bait)
    for line in (best_line, bait_line):
        b = board.copy()
        for u in line: mv = chess.Move.from_uci(u); assert mv in b.legal_moves, f"{e['id']} illegal ply {u}"; b.push(mv)
    ranked = sorted(scores.items(), key=lambda kv: -kv[1])
    cands, seen = [], set()
    for u, _ in ranked:
        if u == e["bait"]: continue
        if u[:2] not in seen: seen.add(u[:2]); cands.append(u[:2])
        if len(cands) == 3: break
    for sq in e["whyTargets"]["squares"]: assert board.piece_at(chess.parse_square(sq)), f"{e['id']} whyTarget {sq} empty"
    out = dict(e); out.update({"tempting": e["bait"], "bestSan": board.san(best), "temptingSan": board.san(bait), "turn": "w",
        "moves": moves, "bestLineUci": best_line, "temptingLineUci": bait_line, "candidates": cands,
        "boss": e["id"] in BOSS, "pack": pack(board), "legal": legal_pack(board)})
    return out

def emit_js(encs):
    js = ["/* GENERATED by tools/build_encounters.py — do not edit by hand. */", "(function(){",
      "  function unpack(e){ var pieces=[], p=e.pack; for (var i=0;i<p.length;i+=4){ pieces.push({color:p[i], role:p[i+1], sq:p[i+2]+p[i+3]}); }",
      "    var legal={}; Object.keys(e.legal).forEach(function(fr){ legal[fr]=e.legal[fr].split(',').map(function(part){ var bits=part.split(':'); var left=bits[0]; return {to:left.replace('x','').slice(2,4), uci:left.replace('x',''), san:bits[1], capture:left.indexOf('x')>=0}; }); });",
      "    e.pieces=pieces; e.legal=legal; return e; }",
      "  var raw = " + json.dumps(encs, separators=(",", ":")) + ";",
      "  window.SHOCKMATE_ENCOUNTERS = raw.map(unpack);", "})();"]
    OUT_JS.write_text("\n".join(js) + "\n")

def main():
    src = json.loads(SRC.read_text()); assert len(src) == 12
    engine = chess.engine.SimpleEngine.popen_uci(sf_path())
    try:
        encs = [build(engine, e) for e in src]
    finally:
        engine.quit()
    OUT_JSON.write_text(json.dumps(encs, indent=1)); emit_js(encs)
    for e in encs:
        m = e["moves"]; tiers = {t: sum(1 for v in m.values() if v["tier"] == t) for t in ("best", "good", "bait", "blunder")}
        print(f"{e['id']} {e['title']:<20} best={m[e['best']]['cp']:>6} bait={m[e['bait']]['cp']:>6} {tiers} bestLine={e['bestLineUci']} baitLine={e['temptingLineUci']} cands={e['candidates']}")

if __name__ == "__main__": main()
