#!/usr/bin/env python3
"""Build data/encounters.v2.json and web/encounters.js from data/encounters.src.json.
Scores every legal move with Stockfish, assigns fairness tiers, derives futures lines from engine PVs,
and asserts the authoring rule (best beats bait by >=150 cp or mate vs no mate). Run: python3 tools/build_encounters.py [--sf PATH]"""
import json, os, re, sys, shutil, chess, chess.engine
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SRCS = [ROOT/"data/encounters.src.json", ROOT/"data/openings.src.json", ROOT/"data/endgames.src.json",
        ROOT/"data/ladder.src.json"]  # ladder: generated by tools/build_ladder.py from the Lichess puzzle db
OUT_JSON, OUT_JS = ROOT/"data/encounters.v2.json", ROOT/"web/encounters.js"
MATE, GOOD_GAP, BEST_GAP, MARGIN, DEPTH, PV_DEPTH, BOSS = 10000, 60, 10, 150, 14, 16, {"04", "08", "12"}

def sf_path():
    if "--sf" in sys.argv: return sys.argv[sys.argv.index("--sf") + 1]
    if os.environ.get("STOCKFISH"): return os.environ["STOCKFISH"]
    win = Path.home() / "tools/stockfish/stockfish/stockfish-windows-x86-64-universal.exe"
    return shutil.which("stockfish") or (str(win) if win.exists() else "/tmp/sf/stockfish/stockfish-ubuntu-x86-64-avx2")

def cp_of(score):
    s = score.pov(chess.WHITE)
    if s.is_mate():
        m = s.mate(); return (MATE - m) if m > 0 else -(MATE + m)
    return s.score()

def truncate_line(board, pv):
    """Ply 1 always. Then add plies until (inclusive) the first capture or mate, max 5."""
    line, b = [], board.copy()
    for i, mv in enumerate(pv[:5]):
        cap, b2 = b.is_capture(mv), b.copy(); b2.push(mv)
        line.append(mv.uci()); b = b2
        if b.is_checkmate() or (i > 0 and cap): break
    # keep only ply 1 if no capture/mate was ever reached
    b = board.copy(); reached = False
    for i, u in enumerate(line):
        mv = chess.Move.from_uci(u); cap = b.is_capture(mv); b.push(mv)
        if b.is_checkmate() or (i > 0 and cap): reached = True
    return line if reached else line[:1]

def pack(board):
    s = ""
    for sq, pc in sorted(board.piece_map().items(), key=lambda kv: chess.square_name(kv[0])):
        s += ("w" if pc.color else "b") + pc.symbol().lower() + chess.square_name(sq)
    return s

def legal_pack(board):
    out = {}
    for mv in board.legal_moves:
        fr = chess.square_name(mv.from_square); san = board.san(mv)
        out.setdefault(fr, []).append(mv.uci() + ("x" if board.is_capture(mv) else "") + ":" + san)
    return {k: ",".join(v) for k, v in out.items()}

def parse_move(board, text):
    """Accept UCI or SAN so opening fights can be authored the way people talk about them.
    A bad or illegal move is an authoring error: report it as a rejection, never a crash."""
    for parse in (chess.Move.from_uci, board.parse_san):
        try:
            mv = parse(text)
        except Exception:
            continue
        if mv in board.legal_moves: return mv
    raise AssertionError(f"move {text!r} is not legal in {board.fen()}")

def unmove(board, e):
    """Glitch's move into a FEN-authored fight: take back `arrive` (source orientation) and prove that
    replaying it from the rebuilt position is legal and lands on exactly this board. A capture names the
    taken piece in `arriveCaptured` (one letter), since a FEN cannot say what used to stand there."""
    assert e.get("arrive"), f"{e['id']} has no arrive move; every fight opens on Glitch's last move"
    mv = chess.Move.from_uci(e["arrive"]); prev = board.copy(stack=False)
    piece = prev.remove_piece_at(mv.to_square)
    assert piece is not None and piece.color != board.turn, f"{e['id']} arrive {mv} must move one of Glitch's pieces"
    prev.set_piece_at(mv.from_square, piece)
    if e.get("arriveCaptured"): prev.set_piece_at(mv.to_square, chess.Piece.from_symbol(
        e["arriveCaptured"].upper() if board.turn == chess.WHITE else e["arriveCaptured"].lower()))
    prev.turn = not board.turn; prev.ep_square = None; prev.halfmove_clock = 0
    assert prev.is_valid(), f"{e['id']} position before arrive {mv} is not a legal position"
    assert mv in prev.legal_moves, f"{e['id']} arrive {mv} is not legal before the fight"
    after = prev.copy(); after.push(mv)
    assert after.board_fen() == board.board_fen() and after.turn == board.turn, f"{e['id']} arrive {mv} does not land on the fight"
    return prev, mv

def prepare(e):
    """Resolve a source entry to a white-to-move position. Opening fights are often authored from
    Black's side; mirroring keeps one board orientation in the arena while teaching the same lesson."""
    e = dict(e)
    if "moves" in e:
        b = chess.Board()
        for san in e["moves"][:-1]: b.push_san(san)
        prev, arrive = b.copy(), b.parse_san(e["moves"][-1])
        b.push(arrive)
        e["fen"] = b.fen()
    else:
        prev, arrive = unmove(chess.Board(e["fen"]), e)
    board = chess.Board(e["fen"])
    best = parse_move(board, e.get("best") or e["bestMove"])
    bait = parse_move(board, e.get("bait") or e["baitMove"])
    if board.turn == chess.BLACK:
        m = lambda mv: chess.Move(chess.square_mirror(mv.from_square), chess.square_mirror(mv.to_square), promotion=mv.promotion)
        board = board.mirror(); best, bait = m(best), m(bait)
        prev, arrive = prev.mirror(), m(arrive)
        e["fen"] = board.fen(); e["mirrored"] = True
        wt = dict(e["whyTargets"])
        wt["squares"] = [chess.square_name(chess.square_mirror(chess.parse_square(s))) for s in wt["squares"]]
        if wt.get("hintSquare"): wt["hintSquare"] = chess.square_name(chess.square_mirror(chess.parse_square(wt["hintSquare"])))
        e["whyTargets"] = wt
        # Mirrored boards need mirrored prose: a bare square name like "f7" is now "f2".
        def flip_text(t):
            return re.sub(r"(?<![A-Za-z0-9])([a-h])([1-8])(?![0-9])",
                          lambda m: m.group(1) + str(9 - int(m.group(2))), t)
        for key in ("hook", "why", "whyLong", "title"):
            if e.get(key): e[key] = flip_text(e[key])
        e["whyTargets"] = dict(e["whyTargets"], prompt=flip_text(e["whyTargets"]["prompt"]))
        e["glitch"] = {k: flip_text(v) for k, v in e["glitch"].items()}
    e["best"], e["bait"] = best.uci(), bait.uci()
    e["arrive"], e["arrivePosition"] = arrive.uci(), pack(prev)
    e.pop("bestMove", None); e.pop("baitMove", None); e.pop("moves", None); e.pop("arriveCaptured", None)
    e.setdefault("pack", "tactics")
    return e

def score_moves(engine, board):
    """White-POV score after every legal move of a white-to-move board."""
    scores = {}
    for mv in board.legal_moves:
        board.push(mv)
        if board.is_checkmate(): scores[mv.uci()] = MATE
        elif board.is_stalemate() or board.is_insufficient_material(): scores[mv.uci()] = 0
        else: scores[mv.uci()] = cp_of(engine.analyse(board, chess.engine.Limit(depth=DEPTH, time=0.8))["score"])
        board.pop()
    return scores

def build(engine, e, scores=None):
    """`scores` lets tools/build_ladder.py hand over the table it already computed with score_moves."""
    e = prepare(e)
    board = chess.Board(e["fen"]); assert board.is_valid(), e["id"]
    best, bait = chess.Move.from_uci(e["best"]), chess.Move.from_uci(e["bait"])
    assert best in board.legal_moves and bait in board.legal_moves, e["id"] + " best/bait illegal"
    if scores is None: scores = score_moves(engine, board)
    top = max(scores.values())
    best_gap = max(e.get("bestTol", BEST_GAP), abs(top) * 0.04)
    good_gap = max(GOOD_GAP, best_gap + 10, abs(top) * 0.12)
    sb, sbait = scores[e["best"]], scores[e["bait"]]
    assert top - sb <= best_gap, f"{e['id']}: engine prefers another move over best {e['best']} ({top} vs {sb})"
    assert (sb >= MATE - 100 and sbait < MATE - 100) or sb - sbait >= MARGIN, f"{e['id']}: margin too small best={sb} bait={sbait}"
    moves = {}
    for mv in board.legal_moves:
        u = mv.uci(); gap = top - scores[u]
        tier = "bait" if u == e["bait"] else "best" if gap <= best_gap else "good" if gap < good_gap else "blunder"
        moves[u] = {"san": board.san(mv), "cp": scores[u], "tier": tier}
    pv_best = engine.analyse(board, chess.engine.Limit(depth=PV_DEPTH, time=1.5), root_moves=[best])["pv"]
    pv_bait = engine.analyse(board, chess.engine.Limit(depth=PV_DEPTH, time=1.5), root_moves=[bait])["pv"]
    best_line, bait_line = truncate_line(board, pv_best), truncate_line(board, pv_bait)
    for line in (best_line, bait_line):
        b = board.copy()
        for u in line: mv = chess.Move.from_uci(u); assert mv in b.legal_moves, f"{e['id']} illegal ply {u}"; b.push(mv)
    # Second-try hint: the origin squares of the strongest moves. The bait's origin stays eligible,
    # so narrowing never hands over the answer by elimination.
    ranked = sorted(scores.items(), key=lambda kv: -kv[1])
    cands, seen = [], set()
    for u, _ in ranked:
        if u[:2] not in seen: seen.add(u[:2]); cands.append(u[:2])
        if len(cands) == 3: break
    if e["best"][:2] not in cands: cands = [e["best"][:2]] + cands[:2]
    # Which position the why-gate should show: the moment where the reason is actually on the board.
    after = board.copy(); after.push(best)
    gate_at = "after"
    for sq in e["whyTargets"]["squares"]:
        s = chess.parse_square(sq); p0, p1 = board.piece_at(s), after.piece_at(s)
        assert p0 is not None, f"{e['id']} whyTarget {sq} empty in the start position"
        if p1 is None or p1.piece_type != p0.piece_type or p1.color != p0.color: gate_at = "before"
    e["whyTargets"] = dict(e["whyTargets"], at=gate_at)
    out = dict(e); out.update({"tempting": e["bait"], "bestSan": board.san(best), "temptingSan": board.san(bait), "turn": "w",
        "moves": moves, "bestLineUci": best_line, "temptingLineUci": bait_line, "candidates": cands,
        "boss": e["id"] in BOSS, "position": pack(board), "legal": legal_pack(board)})
    out.pop("bestTol", None)
    return out

def emit_js(encs):
    js = ["/* GENERATED by tools/build_encounters.py — do not edit by hand. */", "(function(){",
      "  function unpack(e){ var pieces=[], p=e.position; for (var i=0;i<p.length;i+=4){ pieces.push({color:p[i], role:p[i+1], sq:p[i+2]+p[i+3]}); }",
      "    var legal={}; Object.keys(e.legal).forEach(function(fr){ legal[fr]=e.legal[fr].split(',').map(function(part){ var bits=part.split(':'); var left=bits[0]; return {to:left.replace('x','').slice(2,4), uci:left.replace('x',''), san:bits[1], capture:left.indexOf('x')>=0}; }); });",
      "    e.pieces=pieces; e.legal=legal; return e; }",
      "  var raw = " + json.dumps(encs, separators=(",", ":")) + ";",
      "  window.SHOCKMATE_ENCOUNTERS = raw.map(unpack);", "})();"]
    OUT_JS.write_text("\n".join(js) + "\n")

def arrive_only(src):
    """Add or refresh only the arriving move on the built fights. No engine: legality is proved by
    python-chess, and the scored data is left exactly as it was."""
    built = json.loads(OUT_JSON.read_text(encoding="utf-8")); by = {e["id"]: e for e in src}
    for out in built:
        e = prepare(by[out["id"]])
        assert e["fen"] == out["fen"], f"{out['id']} source no longer matches the built fight; run a full build"
        out["arrive"], out["arrivePosition"] = e["arrive"], e["arrivePosition"]
    OUT_JSON.write_text(json.dumps(built, indent=1), encoding="utf-8"); emit_js(built)
    print(f"arrive moves on {len(built)} fights")

def main():
    """--only id[,id] rebuilds just those fights and merges them into the existing output,
    so fixing one board does not mean re-scoring every position. --arrive-only needs no engine."""
    only = None
    if "--only" in sys.argv: only = set(sys.argv[sys.argv.index("--only") + 1].split(","))
    src = []
    for path in SRCS:
        if path.exists(): src += json.loads(path.read_text(encoding="utf-8"))
    ids = [e["id"] for e in src]; assert len(ids) == len(set(ids)), "duplicate encounter ids"
    if "--arrive-only" in sys.argv: return arrive_only(src)
    engine = chess.engine.SimpleEngine.popen_uci(sf_path())
    done = {x["id"]: x for x in json.loads(OUT_JSON.read_text(encoding="utf-8"))} if (only and OUT_JSON.exists()) else {}
    encs = []
    try:
        for e in src:
            if only and e["id"] not in only:
                if e["id"] in done: encs.append(done[e["id"]])
                continue
            try:
                encs.append(build(engine, e))
            except AssertionError as err:
                print("REJECTED", e["id"], e.get("title"), "->", err); continue
    finally:
        engine.quit()
    OUT_JSON.write_text(json.dumps(encs, indent=1), encoding="utf-8"); emit_js(encs)
    for e in encs:
        m = e["moves"]; tiers = {t: sum(1 for v in m.values() if v["tier"] == t) for t in ("best", "good", "bait", "blunder")}
        print(f"{e['pack'][:4]} {e['id']} {e['title']:<20} best={m[e['best']]['cp']:>6} bait={m[e['bait']]['cp']:>6} {tiers} bestLine={e['bestLineUci']} baitLine={e['temptingLineUci']} cands={e['candidates']}")

if __name__ == "__main__": main()
