#!/usr/bin/env node
// web/game.js is GENERATED: the parts in src/game/ concatenated in name order, with this notice on top.
// One closure spans the whole app, so the parts are not modules and are not valid scripts on their own;
// they are slices of one file, cut at the section banners, so a screen can be edited without scrolling
// past the others. Edit a part, then:  npm run build:game     (npm test refuses a stale web/game.js)
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const srcDir = path.join(root, "src", "game");
const target = path.join(root, "web", "game.js");
const NOTICE = "/* GENERATED by tools/build_game.js from src/game/*.js. Edit the parts, then: npm run build:game */\n";

// Line endings are the checkout's business (Windows checkouts get CRLF), not the build's: the parts are
// read whichever way they come, the output is always LF, and the check compares after normalising both.
const lf = (s) => s.replace(/\r\n?/g, "\n");
const parts = fs.readdirSync(srcDir).filter((f) => f.endsWith(".js")).sort();
const built = NOTICE + parts.map((f) => lf(fs.readFileSync(path.join(srcDir, f), "utf8"))).join("");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(target) ? lf(fs.readFileSync(target, "utf8")) : "";
  if (current !== built) {
    console.error("web/game.js is stale or hand-edited. It is generated from src/game/*.js: edit the part, then run  npm run build:game");
    process.exit(1);
  }
  console.log("web/game.js matches src/game/ (" + parts.length + " parts, " + built.length + " chars)");
} else {
  fs.writeFileSync(target, built);
  console.log("wrote web/game.js from " + parts.length + " parts (" + built.length + " chars)");
}
