/* Lesson days. A day is a themed set that mixes packs, so nobody dead-ends inside one pack.
   Every fight belongs to exactly one day. Days 1-8 are hand-authored; bosses close days 1, 2 and 4.
   Days 9+ are the ladder: Lichess puzzles in rising rating bands, written by tools/build_ladder.py. */
(function (root) {
  const BASE = [
    { n: 1, title: "Free Lunch?", blurb: "Glitch leaves food lying around. One plate is poison.", ids: ["01", "o7", "o3", "04"] },
    { n: 2, title: "Two Throats", blurb: "One piece, two targets. He only gets to save one.", ids: ["02", "03", "o2", "12"] },
    { n: 3, title: "Straight Lines", blurb: "Pin him, skewer him, and open the hidden laser.", ids: ["05", "06", "07", "11"] },
    { n: 4, title: "Locked Doors", blurb: "His own pieces shut him in. Knock politely.", ids: ["o1", "g2", "10", "08"] },
    { n: 5, title: "Count First", blurb: "Count attackers, count guards, and only then take.", ids: ["o4", "g3", "t1", "t2", "t3"] },
    { n: 6, title: "Finish It", blurb: "A won game is not won until it is finished.", ids: ["g4", "g1", "o6"] },
    { n: 7, title: "Trade Smart", blurb: "Every swap is a choice. Keep the piece that works.", ids: ["b1", "b2", "k1", "k2"] },
    { n: 8, title: "Hold the Line", blurb: "He attacks first. Answer without giving anything away.", ids: ["d1", "d2", "d3", "d4"] },
  ];
  /* LADDER:START generated by tools/build_ladder.py; do not edit by hand */
  const LADDER = [
    { n: 9, title: "Ladder 1 · 1/4", blurb: "Glitch says 500s can't touch this.", ladder: true, ids: ["L101", "L102", "L103", "L104", "L105"] },
    { n: 10, title: "Ladder 1 · 2/4", blurb: "Glitch says 500s can't touch this.", ladder: true, ids: ["L106", "L107", "L108", "L109", "L110"] },
    { n: 11, title: "Ladder 1 · 3/4", blurb: "Glitch says 500s can't touch this.", ladder: true, ids: ["L111", "L112", "L113", "L114", "L115"] },
    { n: 12, title: "Ladder 1 · 4/4", blurb: "Glitch says 500s can't touch this.", ladder: true, ids: ["L116", "L117", "L118", "L119", "L120"] },
    { n: 13, title: "Ladder 2 · 1/4", blurb: "Glitch says 700s go home crying.", ladder: true, ids: ["L201", "L202", "L203", "L204", "L205"] },
    { n: 14, title: "Ladder 2 · 2/4", blurb: "Glitch says 700s go home crying.", ladder: true, ids: ["L206", "L207", "L208", "L209", "L210"] },
    { n: 15, title: "Ladder 2 · 3/4", blurb: "Glitch says 700s go home crying.", ladder: true, ids: ["L211", "L212", "L213", "L214", "L215"] },
    { n: 16, title: "Ladder 2 · 4/4", blurb: "Glitch says 700s go home crying.", ladder: true, ids: ["L216", "L217", "L218", "L219", "L220"] },
    { n: 17, title: "Ladder 3 · 1/4", blurb: "Glitch says 850s can't touch this.", ladder: true, ids: ["L301", "L302", "L303", "L304", "L305"] },
    { n: 18, title: "Ladder 3 · 2/4", blurb: "Glitch says 850s can't touch this.", ladder: true, ids: ["L306", "L307", "L308", "L309", "L310"] },
    { n: 19, title: "Ladder 3 · 3/4", blurb: "Glitch says 850s can't touch this.", ladder: true, ids: ["L311", "L312", "L313", "L314", "L315"] },
    { n: 20, title: "Ladder 3 · 4/4", blurb: "Glitch says 850s can't touch this.", ladder: true, ids: ["L316", "L317", "L318", "L319", "L320"] },
    { n: 21, title: "Ladder 4 · 1/4", blurb: "Glitch says 1000s need a nap first.", ladder: true, ids: ["L401", "L402", "L403", "L404", "L405"] },
    { n: 22, title: "Ladder 4 · 2/4", blurb: "Glitch says 1000s need a nap first.", ladder: true, ids: ["L406", "L407", "L408", "L409", "L410"] },
    { n: 23, title: "Ladder 4 · 3/4", blurb: "Glitch says 1000s need a nap first.", ladder: true, ids: ["L411", "L412", "L413", "L414", "L415"] },
    { n: 24, title: "Ladder 4 · 4/4", blurb: "Glitch says 1000s need a nap first.", ladder: true, ids: ["L416", "L417", "L418", "L419", "L420"] },
    { n: 25, title: "Ladder 5 · 1/4", blurb: "Glitch says 1150s never beat him. Ever.", ladder: true, ids: ["L501", "L502", "L503", "L504", "L505"] },
    { n: 26, title: "Ladder 5 · 2/4", blurb: "Glitch says 1150s never beat him. Ever.", ladder: true, ids: ["L506", "L507", "L508", "L509", "L510"] },
    { n: 27, title: "Ladder 5 · 3/4", blurb: "Glitch says 1150s never beat him. Ever.", ladder: true, ids: ["L511", "L512", "L513", "L514", "L515"] },
    { n: 28, title: "Ladder 5 · 4/4", blurb: "Glitch says 1150s never beat him. Ever.", ladder: true, ids: ["L516", "L517", "L518", "L519", "L520"] },
    { n: 29, title: "Ladder 6 · 1/4", blurb: "Glitch says 1300s are scared of him.", ladder: true, ids: ["L601", "L602", "L603", "L604", "L605"] },
    { n: 30, title: "Ladder 6 · 2/4", blurb: "Glitch says 1300s are scared of him.", ladder: true, ids: ["L606", "L607", "L608", "L609", "L610"] },
    { n: 31, title: "Ladder 6 · 3/4", blurb: "Glitch says 1300s are scared of him.", ladder: true, ids: ["L611", "L612", "L613", "L614", "L615"] },
    { n: 32, title: "Ladder 6 · 4/4", blurb: "Glitch says 1300s are scared of him.", ladder: true, ids: ["L616", "L617", "L618", "L619", "L620"] },
  ];
  /* LADDER:END */
  const DAYS = BASE.concat(LADDER);

  function dayByNumber(n) { return DAYS.filter((d) => d.n === n)[0] || DAYS[0]; }
  function fightsForDay(all, n) {
    const day = dayByNumber(n), by = {};
    (all || []).forEach((e) => { by[e.id] = e; });
    return day.ids.map((id) => by[id]).filter(Boolean);
  }
  function dayProgress(stats, n) {
    const earned = (stats && stats.cardsEarned) || {}, day = dayByNumber(n);
    const done = day.ids.filter((id) => earned[id]).length;
    return { day: day.n, title: day.title, done: done, total: day.ids.length, complete: done >= day.ids.length };
  }
  // The day he should be on: the first he has not finished, or the last once everything is done.
  function currentDay(stats) {
    for (let i = 0; i < DAYS.length; i++) { if (!dayProgress(stats, DAYS[i].n).complete) return DAYS[i].n; }
    return DAYS[DAYS.length - 1].n;
  }
  function nextDay(n) { return n >= DAYS.length ? null : n + 1; }
  function daysComplete(stats) { return DAYS.filter((d) => dayProgress(stats, d.n).complete).length; }
  // A day is open once the one before it is finished, so the order teaches but nothing is ever locked away for long.
  function dayUnlocked(stats, n) { return n <= 1 || dayProgress(stats, n - 1).complete; }

  const api = { DAYS, dayByNumber, fightsForDay, dayProgress, currentDay, nextDay, daysComplete, dayUnlocked };
  root.ShockmateDays = api;
  if (typeof module !== "undefined") module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
