/* Short explanations, one per hand-authored fight, for a reader at exactly grade level.
   Generated ladder fights (tools/build_ladder.py) bring their own `short`, held to the same rules.
   HAND-AUTHORED ON PURPOSE. The encounter data is generated by tools/build_encounters.py and must
   never be hand-edited, so these live here instead and the build script never overwrites them.

   Rules for anything added here:
   - Nine words maximum. The whole point is that the lesson does not arrive as a paragraph.
   - Say the move first, then why. A kid who stops reading after four words still gets the move.
   - No chess notation, no square names. The board is already on screen saying that.
   - Same lesson as the long line, never a different one. Shorter, not simpler. */
(function (root) {
  const SHORT = {
    "01": "Take the queen. A pawn is a crumb.",
    "02": "One jump bites king and rook.",
    "03": "Your smallest pawn checks him and eats the rook.",
    "04": "Count the guards. Take the one nobody defends.",
    "05": "Pin the knight. It is glued to its king.",
    "06": "It cannot run. Hit it again.",
    "07": "Check him. The rook behind him dies.",
    "08": "Mate beats a pawn hunt.",
    "10": "Mate ends it. Her queen can wait.",
    "11": "Move the knight. The rook fires through it.",
    "12": "Two crowns beat one cookie.",
    "t1": "Do not take yet. Bring another attacker.",
    "t2": "Three hit it. Two guard it. Take.",
    "t3": "Two rooks first. Then the pawn falls.",
    "d1": "Do not run. Check him first.",
    "d2": "His pawn stopped guarding. Take the horse.",
    "d3": "Block with the horse, not the queen.",
    "d4": "The horse guards and chases at once.",
    "o1": "One pawn step. Her queen is blocked.",
    "o2": "Her queen came out early. Punish the loose square.",
    "o3": "Check first. The loose pawn is still there after.",
    "o4": "Horse eats beside his king. Nowhere to hide.",
    "o6": "Hit the rook in the corner. It is trapped.",
    "o7": "Two guards. Take the horse back.",
    "g1": "Mate on the back row. The other move draws.",
    "g2": "Second rook mates. The first guards the escape.",
    "g3": "Take the pawn. Checking loses your rook.",
    "g4": "King first. The pawn can wait.",
    "b1": "Swap your dud bishop for his good one.",
    "b2": "Keep yours. Eat what his cannot guard.",
    "k1": "Locked board. Keep the horse, give the bishop.",
    "k2": "Open board. Trade horses and keep the bishop.",
  };
  const CAP = 9;
  function shortWhy(id) { return SHORT[id] || ""; }
  // Which register a profile reads. The parent sets it; it is never guessed from age or rank.
  // Generated ladder fights carry their own templated `short`; a hand line here always wins.
  function whyFor(enc, wantsShort) {
    if (!enc) return "";
    const s = wantsShort ? (shortWhy(enc.id) || enc.short || "") : "";
    return s || enc.why || "";
  }
  function words(t) { return String(t || "").trim().split(/\s+/).filter(Boolean).length; }

  const api = { SHORT, CAP, shortWhy, whyFor, words };
  root.ShockmateShort = api;
  if (typeof module !== "undefined") module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
